name: Generate Podcast Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repos
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: RickyJasonVanderheyden/podcast-generator@main
        
        
